### ISSUE TITLE
sqliteからpostgreSQLに切り替える（ローカルで環境構築）

### ISSUE THREAD

**Issue by ftnext** [ftnext/my-first-blog-django3#3]
PostgreSQLのインストール の章を進める
https://tutorial-extensions.djangogirls.org/ja/optional_postgresql_installation/

herokuにデプロイするためのステップの1つとして実施する

**Comment by ftnext** [comment]
やること

- [x] ローカルでpostgresの環境構築
- [x] `django-environ`の導入

**Comment by ftnext** [comment]
## ローカルでpostgresの環境構築

Tutorialとは変えてbrewで入れてみる
（結論：Tutorialの方法が一番わかりやすいと思います）

```console
$ brew install postgresql

$ postgres --version
postgres (PostgreSQL) 12.2
$ psql --version
psql (PostgreSQL) 12.2
```
```console
# 環境変数PATHとPGDATAの設定をしてから別タブで
$ postgres
```
ref: 
http://ponsuke-tarou.hatenablog.com/entry/2018/01/31/232012
https://qiita.com/gooddoog/items/1f986c1a6c0f253bd4e2

ユーザとDBの作成（コマンドラインから）

```console
$ createuser -P -e nikkie  # -Pにより対話的にDBユーザのパスワードを入力する
$ createdb djangogirls -e -E utf8 -O nikkie
```

ref:
https://www.postgresql.jp/document/11/html/app-createuser.html
https://www.postgresql.jp/document/11/html/app-createdb.html

psycopg2はpip installでエラー `error: command 'gcc' failed with exit status 1`

    It appears you are missing some prerequisite to build the package from source.

    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

    error: command 'gcc' failed with exit status 1

→psycopg2-binary(==2.8.4)をインストール

TODO：
postgresはUserとDBを作ったが、パスワードの設定などセキュアに使う方法を調べたい（Qiita記事にも言及あり）

**Comment by ftnext** [comment]
## `django-environ` の導入

.envファイルを作成し、settings.pyを編集
ref: https://django-environ.readthedocs.io/en/latest/

ドキュメントの通りの設定では読み込めていないようで
>django.core.exceptions.ImproperlyConfigured: Set the SECRET_KEY environment variable

`env_file`引数を使ったところ解決した
https://stackoverflow.com/a/57479963

このパッケージは2年くらい更新ストップ、かつ、Django2.0まで
動いているが乗り換え先があるなら乗り換えたい

関連：akiyokoさんのDjango本 実践編を参考に、SECRET_KEYを再作成
（GitHubにプッシュして公開しているのとは別のキーを使う）
`python manage.py shell -c 'from django.core.management import utils; print(utils.get_random_secret_key())'`

**Comment by ftnext** [comment]
ローカルで動いているので、このIssueはdone

```console
$ psql -d djangogirls -U nikkie
djangogirls=> select * from blog_post;
```

末尾のセミコロンが重要。入れないとコマンドがどんどんつながっていく

**Comment by ftnext** [comment]
psycopg2のエラーを解決し、2.8系を入れることができた。

**状況**
- `ld: library not found for -lssl`エラーにより`pip install`できなかった
- `xcode-select --install`済み

**解決策**
`env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" pip install psycopg2`
ref: https://stackoverflow.com/a/39244687
日本語で読める例: https://ja.stackoverflow.com/q/61299

ただし、**2.7系を指定して入れることはできていない**
`env LDFLAGS="-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib" pip install --no-cache psycopg2==2.7.*`
エラーメッセージは以下

    It appears you are missing some prerequisite to build the package from source.

    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.

    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).

---

psycopg2がエラーでインストールできていない状態で `pip install django-heroku` すると依存関係によりエラーとなる
その際、psycopg2-binaryが選択肢となる
See: https://github.com/heroku/django-heroku/issues/48

依存関係を変えよう(psycopg2 -> psycopg2-binary)というPR (未マージ) を見つけたが、
https://github.com/heroku/django-heroku/pull/42/files
psycopg2のドキュメントによるとpsycopg2-binaryをモジュールの依存関係に書くのはオススメされないとのこと
https://www.psycopg.org/docs/install.html#binary-install-from-pypi
>If you are the maintainer of a publish package depending on psycopg2 you shouldn’t use ‘psycopg2-binary’ as a module dependency. For production use you are advised to use the source distribution.

**Comment by ftnext** [comment]
参考：WSLの場合の解決方法
https://yoshitaku-jp.hatenablog.com/entry/2020/03/18/123000

**Comment by ABinfinity** [comment]
brew install postgresql
brew reinstall openssl
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
